server:
  port: 5060

spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: secret

  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: nazrin.agha12@gmail.com
#    for using on Windows computer
    password: zswykrdnvcejaise
#    for using on Mac
#    password: fekdpxaloykbxvcp
    port: 587
    properties:
      mail:
        smtp:
          ssl:
            trust: smtp.gmail.com
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false